

services:
  backend:
    build: ./backend
    container_name: penzi_backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:Lotty%40488@db/Penzi_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - penzi_network

  frontend:
    build: ./frontend
    container_name: penzi_frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - penzi_network

  db:
    image: mysql:latest
    container_name: penzi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lotty@488
      
      MYSQL_DATABASE: Penzi_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - penzi_network

volumes:
  mysql_data:

networks:
  penzi_network:
